:commit_subject_prefix:
  :enabled: true
  :severity: :error
  :includes:
    - Add
    - Fix
    - Refactor
    - Remove
    - Update
:commit_subject_suffix:
  :enabled: false
:commit_body_presence:
  :enabled: false
